#!/usr/bin/python3.8
from engine import *

class Game:

    EXPAND = dict(expand=True, fill='both')

    INTRO_LAPSE = 2.0

    W, H = pyautogui.size()

    BG = r"#000000"

    GAME_LAPSE = 30#ms

    def __init__(game):
        ## Tk screen settings
        game.root = tk.Tk()
        game.root.geometry("%ix%i+0+0" %(w,h))
        game.root.attributes("-fullscreen", True)
        game.root.configure(background='black')

        game.menu_images = {
            'title' : tk.PhotoImage(master=game.root, file='data/title.gif')
            'play' : tk.PhotoImage(master=menu.root,file='data/play.gif')
            'exit' : tk.PhotoImage(master=menu.root,file='data/exit.gif')
            'rank' : tk.PhotoImage(master=menu.root,file='data/rank.gif')
            'back' : tk.PhotoImage(master=menu.root,file='data/back_to_menu.gif')
            'controls' : tk.PhotoImage(master=menu.root,file='data/controls.gif')
            'intro' : tk.PhotoImage(master=menu.root,file='data/intro.gif')
        }

        game.sounds = {
            'main_theme' : Sound('data/main_theme.wav'),
            'blaster' : Sound('data/blaster.wav'),
            'tie_blaster' : Sound('data/tie_blaster.wav'),
            'explosion' : Sound('data/explosion.wav'),
        }

        game.images = {
            'millenium_falcon' : Image('data/millenium_falcon.gif'),
            'fighter' : Image('data/fighter.gif'),
            'laser' : Image('data/laser.gif'),
        }

        game.gifs = {
            'explosion' : GIF(game, r'Explosion%d.gif', 1, 7),
            'win' : GIF(game, r'frame_%d_delay-0.1s.gif', 0, 27),
            'lose' : GIF(game, r'Scene%d.gif', 1, 18),
        }

        game.intro = Label(game.root, image=game.menu_images['intro'], bd=0)

        game.menu = Frame(game.root)
    
        game.menu_title = Label(game.menu, bg='black',image=game.menu_images['title'],height=210,bd=0)
        game.menu_title.pack(side='top')
    
        game.menu_play = Label(game.menu, bg='black', game.menu_images['play'],height=90,bd=0)
        game.menu_play.pack()
        game.menu_play.bind("<Button-1>", game.menu_play_func)
    
        game.menu_rank = Label(game.menu, image=game.menu_images['rank'],height=90,bg='black',bd=0)
        game.menu_rank.pack()
        game.menu_rank.bind("<Button-1>", game.menu_rank_func)
    
        game.menu_exit = Label(game.menu, bg='black', image=game.menu_images['exit'],height=90,bd=0)
        game.menu_exit.pack()
        game.menu_exit.bind("<Button-1>", game.menu_exit_func)
    
        game.menu_controls = Label(game.menu, image=game.menu_images['controls'],bd=0)
        game.menu_controls.pack(side='bottom')

        game.rank = Frame(game.root)

        game.rank_rank = Label(game.rank, bg='black',height=500,width=100)
        game.rank_rank.pack(side='top')

        game.rank_back = Label(game.rank, bg='black', image=game.menu_images['back'],height=150,bd=0)
        game.rank_back.pack()
        game.rank_back.bind("<Button-1>", game.rank_back_func)
    
        game.game = Frame(game.root)

        game.canvas = Canvas(game.game, width=game.W, height=game.H, bg=game.BG)
        game.canvas.pack(**game.EXPAND)

        #=================================================#
        #               :: MOVIMENTO ::                   #
        game.root.bind("<KeyPress-Up>"  ,game.p_up)       #
        game.root.bind("<KeyRelease-Up>",game.r_up)       #
                                                          #
        game.root.bind("<KeyPress-Down>"  ,game.p_down)   #
        game.root.bind("<KeyRelease-Down>",game.r_down)   #
                                                          #
        game.btn_up   = False                             #
        game.btn_down = False                             #
                                                          #        
        game.root.bind("<KeyPress-Left>"   ,game.p_left)  #   Esse trecho implementa
        game.root.bind("<KeyRelease-Left>" ,game.r_left)  #   os comandos referentes
                                                          #   as teclas.
        game.root.bind("<KeyPress-Right>"   ,game.p_right)#
        game.root.bind("<KeyRelease-Right>" ,game.r_right)#
                                                          #
        game.btn_left = False                             #
        game.btn_right = False                            #
        #                :: OUTROS ::                     #
        game.root.bind("<KeyPress-space>"  , game.p_shot) #
        game.root.bind("<KeyRelease-space>", game.r_shot) #
                                                          #
        game.btn_shot = False                             #
        game.btn_shot_cooldown = True                     #
        #=================================================#


        #=================================================#
        game.start_time = None
        
        game.objects = []

        #=================================================#

        game.score = Frame(game.game)

        game.score_fighters = Frame(game.score)
        game.score_fighters.pack(side='top')

        game.score_fighters_text = Label(game.score_fighters, text="Fighters:")
        game.score_fighters_text.pack(side='left')

        game.score_fighters_num = Label(game.score_fighters, text="0")
        game.score_fighters_num.pack(side='left')

        game.score_time = Frame(game.score)
        game.score_time.pack(side='top')

        game.score_time_text = Label(game.score_time, text="Fighters:")
        game.score_time_text.pack(side='left')

        game.score_time_num = Label(game.score_time, text="0.0")
        game.score_time_num.pack(side='left')

        game.record = Frame(game.game)
        
        game.record_question = Label(game.record, text = "Enter your name:",fg='white',bg='black')
        game.record_question.pack()

        game.record.bind('<Return>', game.save_score)

        game.player_name = StringVar()

        game.record_answer = Entry(game.record, textvariable=game.player_name)
        game.record_answer.pack()


    def menu_play_func(game):
        ## Switch from Menu to Canvas
        game.menu.pack_forget()
        game.game.pack(**game.EXPAND)

        ## Start game
        game.play()

    def menu_exit_func(game):
        ## Close Sounds
        for sound in game.sounds.values():
            sound.close()

        ## Close Screen
        game.root.destroy()
    
    def menu_rank_func(game):
        ## Switch to ranking
        game.menu.pack_forget()
        game.rank.pack()
    
    def rank_back_func(game):
        ## Switch back to menu
        game.rank.pack_forget()
        game.menu.pack()

    def start(game):
        ## Show Intro Image
        game.intro.pack(anchor='center')

        ## Start playing main theme
        game.sounds['intro'].loop()

        sleep(game.INTRO_LAPSE)

        ## Switch to menu
        game.intro.pack_forget()
        game.menu.pack(**game.EXPAND)

    def play(game):
        ...
        game.start_time = clock()
        ...

    def update(game):
        ...

    def end(game):
        ...
        game.record.place(relx=0.5, rely=0.5)
        game.record_answer.focus()
        ...

    ## ===================== ##

    def p_shot(game, event):
        game.btn_shot = True
        
    def r_shot(game, event):
        game.btn_shot = False
        game.btn_shot_cooldown = True
        
    def p_up(game, event):
        game.btn_up = True
    def r_up(game, event):
        game.btn_up = False

    def p_down(game, event):
        game.btn_down = True
    def r_down(game, event):
        game.btn_down = False
    
    def p_left(game, event):
        game.btn_left = True
    def r_left(game, event):
        game.btn_left = False

    def p_right(game, event):
        game.btn_right = True
    def r_right(game, event):
        game.btn_right = False

    ## ===================== ##

    @property
    def time(game):
        return clock() - game.start_time

    @property
    def score(game):
        return game.time * 2
        ...

    """
    A funcao game.GameOver decreta o
    fim do jogo apos uma saudacao.
    """
    "================="

    
    def atirarMF(game):
        if game.shotbtn and game.cooldown:
            X,Y = game.Space.coords(game.MF)
##            game.root.after(10,play_sound, "blaster.wav")
            
            game.tirosrebeldes.append(game.Space.create_image(X,Y-60,
                                                              image=game.LASER_img))
            game.cooldown = False
    "======================="    

    def fire_fighter(game, fighter):
##        game.root.after(10,play_sound, "tie_blaster.wav")
        
        game.tirosdoImperio.append(game.Space.create_image(
                                   game.Space.coords(fighter)[0],
                                   game.Space.coords(fighter)[1]+30,
                                   image=game.LASER_img))
                                   
    def checkColisaoFighterMF(game):
        a,b = game.Space.coords(game.MF)[0],game.Space.coords(game.MF)[1]
        for fighter in game.Fighters:
            x,y = game.Space.coords(fighter)[0],game.Space.coords(fighter)[1]
            if ((a-x)**2+(b-y)**2)**0.5<40:
                game.Kaboom(fighter)
                game.Space.create_image(game.Space.coords(game.MF)[0],
                                        game.Space.coords(game.MF)[1],
                                        image=game.Explosion[4])
                game.GameOver()
            
    def VishSeraQueAtingiuAMillenium(game,laser,MF):
        try:
            verificacao=[abs(game.Space.coords(laser)[0]-game.Space.coords(MF)[0])<29,
                         game.Space.coords(MF)[1]-game.Space.coords(laser)[1]<20,
                         game.Space.coords(laser)[1]-game.Space.coords(MF)[1]<20]
        except:
            verificacao=[False,False,False]
            
        if all(verificacao):
            game.Space.create_image(game.Space.coords(MF)[0],
                                    game.Space.coords(MF)[1],
                                    image=game.Explosion[4])
            game.Space.delete(laser)
            game.tirosdoImperio.remove(laser)
            game.GameOver()

    def SeraQueDestruiuOsInimigo(game,laser,lista):
        for malvadao in lista:
            try:
                verificacao=[abs(game.Space.coords(laser)[0]-game.Space.coords(malvadao)[0])<20,
                             game.Space.coords(laser)[1]-game.Space.coords(malvadao)[1]<15,
                             game.Space.coords(malvadao)[1]-game.Space.coords(laser)[1]<15]
            except:
                verificacao=[False,False,False]
                
            if all(verificacao):
                game.Kaboom(malvadao, laser)
                
    def Kaboom(game, AsInimigx, laser=None):
        contador=0
        explosion=[]
        def explodindo(coordsdAsInimigx,coordslaser,contador,explosion,check=True):
            if contador>1:
                for gifAntigo in explosion:
                    game.Space.delete(gifAntigo)
                    explosion.remove(gifAntigo)
            
            if contador==0:
                game.Space.delete(AsInimigx)      
                game.Fighters.remove(AsInimigx)
            
            if contador<7: 
                explosion.append(game.Space.create_image(
                             coordslaser[0],coordsdAsInimigx[1],
                             image=game.Explosion[contador]))
                contador+=1
                game.root.after(120,explodindo,coordsdAsInimigx,coordslaser,contador,explosion)           
            if contador==7:
                game.Space.delete(explosion[0])
        
        if laser!=None:
##            thread.start_new_thread(play_sound, ("explosion.wav",))
            explodindo(game.Space.coords(AsInimigx),game.Space.coords(laser),contador,explosion)
            game.Space.delete(laser)      
            game.tirosrebeldes.remove(laser)
            game.score += 1
            game.scoreboard['text'] = 'fighters: %d'%game.score
            game.levelincrease()
        if laser==None:
            explodindo(game.Space.coords(AsInimigx),game.Space.coords(AsInimigx),contador,explosion,False)
        
    def TheBirthOfAnAsteroid(game,x,y,asteroid='random'):
        vetor = (3*cos(pi*random()), 4 + 6*random())
        if asteroid == 'random':
            game.AsteroidsPlaced+=[((game.Space.create_image(x,y,image=choice(game.Asteroids))), vetor)]
        else:
            game.AsteroidsPlaced+=[game.Space.create_image(x,y,image=asteroid), vetor]
            
    def CuidadoComOsAsteroide(game, asteroide):
        a,b = game.Space.coords(asteroide)[0],game.Space.coords(asteroide)[1]
        for fighter in game.Fighters:
            x,y = game.Space.coords(fighter)[0],game.Space.coords(fighter)[1]
            if ((a-x)**2+(b-y)**2)**0.5<55:
                game.Kaboom(fighter)
                
        x,y = game.Space.coords(game.MF)[0],game.Space.coords(game.MF)[1]
        if ((a-x)**2+(b-y)**2)**0.5<70:
            game.Space.create_image(game.Space.coords(game.MF)[0],
                                    game.Space.coords(game.MF)[1],
                                    image=game.Explosion[4])
            game.GameOver()

    def levelincrease(game):
        if game.score%10*game.nivel == 0:
            game.nivel += 1

    def LaserBeams(game):
           
        for tiro in game.tirosrebeldes:
            """movendo os tiros rebeldes pra cima"""
            game.Space.move(tiro,0,-15)
            
            if game.Space.coords(tiro)[1]<0: # Pra nao sobrecarregar
                game.Space.delete(tiro)      # o programa
                game.tirosrebeldes.remove(tiro)
                
            else:
                 game.SeraQueDestruiuOsInimigo(tiro, game.Fighters)
            
        for tiro in game.tirosdoImperio:
            """e os tiros do Imperio pra baixo"""
            game.Space.move(tiro,0,15)
            if game.Space.coords(tiro)[1]>game.LY: # Pra nao sobrecarregar
                game.Space.delete(tiro)            # o programa
                game.tirosdoImperio.remove(tiro)     
            game.VishSeraQueAtingiuAMillenium(tiro,game.MF)

def main():
    menu = Menu()
    
if  __name__ == '__main__':
    main()
   
    
